context:
  version: "1.15.0"

package:
  name: create-qwik
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-qwik/-/create-qwik-${{ version }}.tgz
  sha256: 132f5fee66e839ba685c76b1641fed45bf76cd4d0bf0de98d57bf54a49473821

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - create-qwik --help

about:
  license: MIT
  license_file: LICENSE
  summary: Interactive CLI for create Qwik projects and adding features.
  homepage: https://qwik.dev/
  repository: https://github.com/QwikDev/qwik

extra:
  recipe-maintainers:
    - danielnachun
