context:
  version: "1.20.0"

package:
  name: create-qwik
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-qwik/-/create-qwik-${{ version }}.tgz
  sha256: ed50fec6e5e00680aca0a8262886b9f88287a308bbd243b8a411e50eb9a2ea5c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - create-qwik --help

about:
  license: MIT
  license_file: LICENSE
  summary: Interactive CLI for create Qwik projects and adding features.
  homepage: https://qwik.dev/
  repository: https://github.com/QwikDev/qwik

extra:
  recipe-maintainers:
    - danielnachun
