context:
  version: "1.20.1"

package:
  name: create-qwik
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-qwik/-/create-qwik-${{ version }}.tgz
  sha256: e803b66566278a4a9345b39be4eb43b73f88b40cb2f7cf5b255028e7946c3807

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - create-qwik --help

about:
  license: MIT
  license_file: LICENSE
  summary: Interactive CLI for create Qwik projects and adding features.
  homepage: https://qwik.dev/
  repository: https://github.com/QwikDev/qwik

extra:
  recipe-maintainers:
    - danielnachun
