context:
  version: "1.17.1"

package:
  name: create-qwik
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-qwik/-/create-qwik-${{ version }}.tgz
  sha256: 15f1c1b9836d5b33fdacf4d62819d3a592abf196ec59c09612533a045e7bdf43

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - create-qwik --help

about:
  license: MIT
  license_file: LICENSE
  summary: Interactive CLI for create Qwik projects and adding features.
  homepage: https://qwik.dev/
  repository: https://github.com/QwikDev/qwik

extra:
  recipe-maintainers:
    - danielnachun
