context:
  version: "1.19.2"

package:
  name: create-qwik
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-qwik/-/create-qwik-${{ version }}.tgz
  sha256: ccf14743d54ed9a37426dd30afd78ad02a18deda248c807f14142a818b8a4e1c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - create-qwik --help

about:
  license: MIT
  license_file: LICENSE
  summary: Interactive CLI for create Qwik projects and adding features.
  homepage: https://qwik.dev/
  repository: https://github.com/QwikDev/qwik

extra:
  recipe-maintainers:
    - danielnachun
